const express = require("express")
const router = express.Router()
const {authorized}= require("../models/common/auth")
const creatorController = require("../controllers/creator")
const creatorValidation = require("../Validations/creator")
const contentController = require("../controllers/content")
const contentVallidation = require("../Validations/content")
const commentController = require("../controllers/comment")
const dashController = require("../controllers/dashboard")
router.post("/register",creatorValidation.addCreator,creatorController.creatorRegistration)
router.post("/login",creatorValidation.loginnCreator,creatorController.loginCreator)
router.post("/content",authorized,contentVallidation.addContent,contentController.contentCreate)
router.get("/contentDetails",authorized,contentController.getContent)
router.get("/contentById",authorized,contentController.getContentById )
router.put("/content",authorized,contentController.updateContent)
router.delete("/content",authorized,contentController.deleteContent)
router.post("/comment",authorized,commentController.createComment)
router.get("/dashboard",authorized, dashController.gettingData)
router.get("/dashboardById",authorized,dashController.gettingDataById)

module.exports=router